basePath: /api/v1
definitions:
  query.GetOrderDto:
    properties:
      orderView:
        $ref: '#/definitions/query.OrderView'
        type: object
    type: object
  query.GetOrdersDto:
    properties:
      orderViews:
        items:
          $ref: '#/definitions/query.OrderView'
        type: array
    type: object
  query.OrderView:
    properties:
      id:
        type: string
      status:
        type: integer
    type: object
host: localhost:8080
info:
  contact: {}
  description: order context
  license: {}
  title: Order Application
  version: "1.0"
paths:
  /orders:
    get:
      consumes:
      - application/json
      description: Get all orders
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/query.GetOrdersDto'
      summary: Get orders
      tags:
      - order
    post:
      consumes:
      - application/json
      description: Create a new order
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            type: string
      summary: Create a order
      tags:
      - order
  /orders/{id}:
    get:
      consumes:
      - application/json
      description: Get order
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/query.GetOrderDto'
      summary: Get order
      tags:
      - order
  /orders/cancel/{id}:
    put:
      consumes:
      - application/json
      description: Cancel the order
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            type: string
      summary: Cancel order
      tags:
      - order
  /orders/pay/{id}:
    put:
      consumes:
      - application/json
      description: Pay the order
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            type: string
      summary: Pay order
      tags:
      - order
  /orders/ship/{id}:
    put:
      consumes:
      - application/json
      description: ship the order
      parameters:
      - description: id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            type: string
      summary: Ship order
      tags:
      - order
swagger: "2.0"
