apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: go-ddd
  name: go-ddd
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-ddd
  template:
    metadata:
      labels:
        app: go-ddd
    spec:
      containers:
        - image: go-ddd
          name: go-ddd
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 3
