# Default values for goddd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: "goddd"
  pullPolicy: "IfNotPresent"

autoscaling:
  enabled: "false"

replicaCount: 2

service:
  type: NodePort
  port: 80