# Default values for go-ddd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: "docker-go-ddd"
  tag: "latest"
  pullPolicy: "IfNotPresent"

autoscaling:
  enabled: "false"

replicaCount: 2

service:
  type: NodePort
  port: 8080

serviceAccount:
  # Specifies whether a service account should be created
  enabled: false
  # List of image pull secrets if pulling from private registries
  imagePullSecrets: []

podDisruptionBudget: {}