# Default values for go-ddd.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: "docker-go-ddd"
  tag: "latest"
  pullPolicy: "IfNotPresent"

autoscaling:
  enabled: "false"

replicaCount: 2

service:
  type: NodePort
  port: 8080